### ISSUE TITLE
BACKEND_SERVICE works with `odo link`

### ISSUE THREAD

**Issue by ryanj** [openshift-evangelists/Wild-West-Frontend#2]

**Comment by jorgemoralespou** [comment]
@ryanj thanks for this, but the idea was that instead of having to configure a route to the backend service so that the web directly talks to the backend via a route, instead it should talk to the server part and this should direct/proxy the request to the service for the backend and not the route, like the parksmap app do, so you can link the backend service into the frontend deployment and it just works.

With this method, we still need to pass the backend route, which can not easily be linked via odo.

**Comment by ryanj** [comment]
@jorgemoralespou take a look at PR #4 and let me know if that solves this issue

**Comment by jorgemoralespou** [comment]
@ryanj haven't been able to make it work.
